# Generated by Django 3.1.2 on 2020-11-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emaild', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('isadmin', models.BooleanField(default=False)),
            ],
        ),
    ]
