# Generated by Django 3.1.3 on 2020-11-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highestbid',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
