# Generated by Django 3.1.3 on 2020-11-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_highestbid_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highestbid_userid',
        ),
    ]
